CREATE TABLE "ORDER" (
	"ORDER_NUM"	NUMBER		NOT NULL,
	"PAYMENT_NUM"	NUMBER		NOT NULL,
	"NOV_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"ORDER_DATE"	DATE		NULL,
	"ORDER_COUNT"	NUMBER		NULL,
	"ORDER_CANCEL_OR_NOT"	CHAR(2)		NULL
);

CREATE TABLE "PAYMENT" (
	"PAYMENT_NUM"	NUMBER		NOT NULL,
	"PAYMENT_DATE"	DATE		NULL,
	"PAYMENT_PRICE"	NUMBER		NULL,
	"PAYMENT_TYPE"	VARCHAR2(6)		NULL
);

CREATE TABLE "Untitled12" (
	"Key"	VARCHAR(255)		NOT NULL,
	"Field"	VARCHAR(255)		NULL,
	"Field2"	VARCHAR(255)		NULL,
	"Field3"	VARCHAR(255)		NULL,
	"Field4"	VARCHAR(255)		NULL
);

CREATE TABLE "QNA" (
	"POST_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"QNA_TITLE"	VARCHAR2(100)		NULL,
	"QNA_OPEN_YN"	CHAR(2)		NULL,
	"QNA_REPLY_YN"	CHAR(2)		NULL,
	"QNA_DATE"	DATE		NULL
);

CREATE TABLE "NOTICE" (
	"NOTICE_NUM"	NUMBER		NOT NULL,
	"NOTICE_DATE"	DATE		NULL,
	"NOTICE_NAME"	VARCHAR2(40)		NULL,
	"NOTICE_VIEW_COUNT"	NUMBER		NULL,
	"NOTICE_CONTENT"	VARCHAR2(2000)		NULL
);

CREATE TABLE "GENRE_CATEGORY" (
	"CATEGORY_CODE"	VARCHAR2(5)		NULL,
	"CATEGORY_NAME"	VARCHAR2(14)		NULL
);

CREATE TABLE "QNA_REPLY" (
	"REPLY_NUM"	NUMBER		NOT NULL,
	"POST_NUM"	NUMBER		NOT NULL,
	"REPLY_DATE"	DATE		NULL,
	"REPLY_ID"	VARCHAR2(12)		NULL,
	"REPLY_CONTENT"	VARCHAR2(600)		NULL
);

CREATE TABLE "SHOPPING_CART" (
	"NOV_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"CART_COUNT"	NUMBER		NULL
);

CREATE TABLE "WEB_NOV_INFO" (
	"WEB_NOV_NUM"	VARCHAR2(8)		NOT NULL,
	"CATEGORY_CODE"	VARCHAR2(5)		NULL,
	"WEB_NOV_TITLE"	VARCHAR2(20)		NULL,
	"WEB_NOV_AUTHOR"	VARCHAR2(20)		NULL,
	"CHAP_PER_COIN"	NUMBER		NULL,
	"WEB_NOV_PUBLISHER"	VARCHAR2(20)		NULL,
	"WEB_NOV_INFORM"	VARCHAR2(1200)		NULL,
	"WEB_NOV_IMG_LOCATION"	VARCHAR2(100)		NULL,
	"DAY_OF_WEEK"	VARCHAR2(3)		NULL,
	"WEB_NOV_OPEN_OR_CLOSE"	CHAR(2)		NULL,
	"FINISHED_OR_NOT"	CHAR(2)		NULL
);

CREATE TABLE "NOV_REVIEW" (
	"NOV_REVIEW_NUM"	NUMBER		NOT NULL,
	"NOV_NUM"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NULL,
	"REVIEW_DATE"	DATE		NULL,
	"NOV_CONTENT"	VARCHAR2(2000)		NULL
);

CREATE TABLE "MEM_INFO" (
	"MEM_NUM"	NUMBER		NOT NULL,
	"MEM_NAME"	VARCHAR2(15)		NULL,
	"MEM_ID"	VARCHAR2(12)		NULL,
	"MEM_PWD"	VARCHAR2(12)		NULL,
	"MEM_EMAIL"	VARCHAR2(320)		NULL,
	"MEM_ADDRESS"	VARCHAR2(320)		NULL,
	"MEM_BIRTHDATE"	DATE		NULL,
	"MEM_LOGIN_COUNT"	NUMBER		NULL,
	"MEM_COIN"	NUMBER		NULL,
	"MEM_CAN_VOTE_YN"	CHAR(2)		NULL,
	"MEM_WITHDRAW_YN"	CHAR(2)		NULL,
	"MEM_WITHDRAW_DATE"	DATE		NULL,
	"MEM_CLASS"	VARCHAR2(10)		NULL,
	"MEM_BLOCK_YN"	CHAR(2)		NULL,
	"MEM_BLOCK_DATE"	DATE		NULL,
	"MEM_ENROLL_DATE"	DATE		NULL
);

CREATE TABLE "BOOKSHELF" (
	"BOOKSHELF_NUM"	NUMBER		NOT NULL,
	"WEB_NOV_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"CHAPTER_NUM"	NUMBER		NULL
);

CREATE TABLE "USUAL_FAQ" (
	"POST_NUM"	NUMBER		NOT NULL,
	"FAQ_POST_TITLE"	VARCHAR2(300)		NULL,
	"FAQ_POST_CONTENT"	VARCHAR2(400)		NULL
);

CREATE TABLE "COMPET_LIST" (
	"COMPET_DETAIL_NUM"	VARCHAR2(30)		NOT NULL,
	"COMPET_NUM"	VARCHAR2(15)		NULL,
	"NOV_CONTENT"	VARCHAR2(1000)		NULL,
	"CHAPTER_NUM"	NUMBER		NULL
);

CREATE TABLE "STOCK" (
	"NOV_NUM"	NUMBER		NOT NULL,
	"NOV_INPUT"	NUMBER		NULL,
	"NOV_OUTPUT"	NUMBER		NULL
);

CREATE TABLE "Untitled24" (
	"COIN_SAVINGS_NUM"	NUMBER		NOT NULL,
	"SAVINGS_DATE"	DATE		NULL,
	"PER_SAVINGS_RATE"	NUMBER		NULL,
	"FREE_COIN_OR_NOT"	CHAR(2)		NULL
);

CREATE TABLE "WEB_NOV_DETAIL" (
	"WEB_NOV_DETAIL_NUM"	NUMBER		NOT NULL,
	"WEB_NOV_NUM"	NUMBER		NOT NULL,
	"PAY_OR_NOT"	CHAR(2)		NULL,
	"WEB_NOV_CONTENT"	VARCHAR2(2000)		NULL,
	"CHAPTER_NUM"	NUMBER		NOT NULL
);

CREATE TABLE "NOV_INFO" (
	"NOV_NUM"	NUMBER		NOT NULL,
	"CATEGORY_CODE"	VARCHAR2(5)		NULL,
	"NOV_TITLE"	VARCHAR2(20)		NULL,
	"NOV_AUTHOR"	VARCHAR2(20)		NULL,
	"NOV_PRICE"	NUMBER		NULL,
	"NOV_PUBLISHER"	VARCHAR2(20)		NULL,
	"NOV_INFORM"	VARCHAR2(1200)		NULL,
	"NOV_IMG_LOCATION"	VARCHAR2(100)		NULL,
	"ORDERABLE_YN"	CHAR(2)		NULL,
	"NOV_AMOUNT"	NUMBER		NULL
);

CREATE TABLE "WISHLIST" (
	"WEB_NOV_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL
);

CREATE TABLE "WEB_NOV_REPLY" (
	"REPLY_NUM"	NUMBER		NOT NULL,
	"WEB_NOV_NUM"	NUMBER		NOT NULL,
	"REPLY_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(12)		NULL,
	"REPLY_CONTENT"	VARCHAR2(600)		NULL
);

CREATE TABLE "COIN_USE_HIS" (
	"COIN_USE_NUM"	NUMBER		NOT NULL,
	"WEB_NOV_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"COIN_USE_DATE"	DATE		NULL,
	"COIN_USAGE"	NUMBER		NULL,
	"CHAPTER_NUM"	NUMBER		NULL
);

CREATE TABLE "COIN_CHARGE" (
	"COIN_CHARG_NUM"	NUMBER		NOT NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"COIN_CHARGE_DATE"	DATE		NULL,
	"COIN_CHARGE_COUNT"	NUMBER		NULL,
	"COIN_CHARGE_TOTAL"	NUMBER		NULL,
	"WEEKLY_COIN_YN"	CHAR(2)		NULL
);

CREATE TABLE "COMPET_INFO" (
	"COMPET_NUM"	NUMBER		NULL,
	"MEM_NUM"	NUMBER		NOT NULL,
	"COMPET_PAPER_YN"	CHAR(2)		NULL,
	"NOV_TITLE"	VARCHAR2(20)		NULL,
	"NOV_INFO"	VARCHAR2(2000)		NULL,
	"COMPET_SSN"	NUMBER		NULL,
	"COMPET_NOV_IMG_LOCATION"	VARCHAR2(200)		NULL,
	"SCORE"	NUMBER		NULL,
	"COMPET_ACT_YN"	CHAR(4)		NULL
);

CREATE TABLE "ACCUM_REPORT" (
	"REPLY_NUM"	NUMBER		NOT NULL,
	"ACCUM_REPORT_NUM"	NUMBER		NULL
);

CREATE TABLE "COMPET_FIXTURE" (
	"FIXTURE_NUM"	NUMBER		NOT NULL,
	"COMPET_NUM"	NUMBER		NULL,
	"FIXTURE_STAT"	NUMBER		NULL
);

ALTER TABLE "ORDER" ADD CONSTRAINT "PK_ORDER" PRIMARY KEY (
	"ORDER_NUM"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT_NUM"
);

ALTER TABLE "Untitled12" ADD CONSTRAINT "PK_UNTITLED12" PRIMARY KEY (
	"Key"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"POST_NUM"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NUM"
);

ALTER TABLE "GENRE_CATEGORY" ADD CONSTRAINT "PK_GENRE_CATEGORY" PRIMARY KEY (
	"CATEGORY_CODE"
);

ALTER TABLE "QNA_REPLY" ADD CONSTRAINT "PK_QNA_REPLY" PRIMARY KEY (
	"REPLY_NUM"
);

ALTER TABLE "SHOPPING_CART" ADD CONSTRAINT "PK_SHOPPING_CART" PRIMARY KEY (
	"NOV_NUM",
	"MEM_NUM"
);

ALTER TABLE "WEB_NOV_INFO" ADD CONSTRAINT "PK_WEB_NOV_INFO" PRIMARY KEY (
	"WEB_NOV_NUM"
);

ALTER TABLE "NOV_REVIEW" ADD CONSTRAINT "PK_NOV_REVIEW" PRIMARY KEY (
	"NOV_REVIEW_NUM"
);

ALTER TABLE "MEM_INFO" ADD CONSTRAINT "PK_MEM_INFO" PRIMARY KEY (
	"MEM_NUM"
);

ALTER TABLE "BOOKSHELF" ADD CONSTRAINT "PK_BOOKSHELF" PRIMARY KEY (
	"BOOKSHELF_NUM"
);

ALTER TABLE "USUAL_FAQ" ADD CONSTRAINT "PK_USUAL_FAQ" PRIMARY KEY (
	"POST_NUM"
);

ALTER TABLE "COMPET_LIST" ADD CONSTRAINT "PK_COMPET_LIST" PRIMARY KEY (
	"COMPET_DETAIL_NUM",
	"COMPET_NUM"
);

ALTER TABLE "STOCK" ADD CONSTRAINT "PK_STOCK" PRIMARY KEY (
	"NOV_NUM"
);

ALTER TABLE "Untitled24" ADD CONSTRAINT "PK_UNTITLED24" PRIMARY KEY (
	"COIN_SAVINGS_NUM"
);

ALTER TABLE "WEB_NOV_DETAIL" ADD CONSTRAINT "PK_WEB_NOV_DETAIL" PRIMARY KEY (
	"WEB_NOV_DETAIL_NUM",
	"WEB_NOV_NUM"
);

ALTER TABLE "NOV_INFO" ADD CONSTRAINT "PK_NOV_INFO" PRIMARY KEY (
	"NOV_NUM"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"WEB_NOV_NUM",
	"MEM_NUM"
);

ALTER TABLE "WEB_NOV_REPLY" ADD CONSTRAINT "PK_WEB_NOV_REPLY" PRIMARY KEY (
	"REPLY_NUM"
);

ALTER TABLE "COIN_USE_HIS" ADD CONSTRAINT "PK_COIN_USE_HIS" PRIMARY KEY (
	"COIN_USE_NUM"
);

ALTER TABLE "COIN_CHARGE" ADD CONSTRAINT "PK_COIN_CHARGE" PRIMARY KEY (
	"COIN_CHARG_NUM"
);

ALTER TABLE "COMPET_INFO" ADD CONSTRAINT "PK_COMPET_INFO" PRIMARY KEY (
	"COMPET_NUM"
);

ALTER TABLE "ACCUM_REPORT" ADD CONSTRAINT "PK_ACCUM_REPORT" PRIMARY KEY (
	"REPLY_NUM"
);

ALTER TABLE "COMPET_FIXTURE" ADD CONSTRAINT "PK_COMPET_FIXTURE" PRIMARY KEY (
	"FIXTURE_NUM"
);

ALTER TABLE "SHOPPING_CART" ADD CONSTRAINT "FK_NOV_INFO_TO_SHOPPING_CART_1" FOREIGN KEY (
	"NOV_NUM"
)
REFERENCES "NOV_INFO" (
	"NOV_NUM"
);

ALTER TABLE "SHOPPING_CART" ADD CONSTRAINT "FK_MEM_INFO_TO_SHOPPING_CART_1" FOREIGN KEY (
	"MEM_NUM"
)
REFERENCES "MEM_INFO" (
	"MEM_NUM"
);

ALTER TABLE "COMPET_LIST" ADD CONSTRAINT "FK_COMPET_INFO_TO_COMPET_LIST_1" FOREIGN KEY (
	"COMPET_NUM"
)
REFERENCES "COMPET_INFO" (
	"COMPET_NUM"
);

ALTER TABLE "STOCK" ADD CONSTRAINT "FK_NOV_INFO_TO_STOCK_1" FOREIGN KEY (
	"NOV_NUM"
)
REFERENCES "NOV_INFO" (
	"NOV_NUM"
);

ALTER TABLE "WEB_NOV_DETAIL" ADD CONSTRAINT "FK_WEB_NOV_INFO_TO_WEB_NOV_DETAIL_1" FOREIGN KEY (
	"WEB_NOV_NUM"
)
REFERENCES "WEB_NOV_INFO" (
	"WEB_NOV_NUM"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_WEB_NOV_INFO_TO_WISHLIST_1" FOREIGN KEY (
	"WEB_NOV_NUM"
)
REFERENCES "WEB_NOV_INFO" (
	"WEB_NOV_NUM"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEM_INFO_TO_WISHLIST_1" FOREIGN KEY (
	"MEM_NUM"
)
REFERENCES "MEM_INFO" (
	"MEM_NUM"
);

ALTER TABLE "ACCUM_REPORT" ADD CONSTRAINT "FK_WEB_NOV_REPLY_TO_ACCUM_REPORT_1" FOREIGN KEY (
	"REPLY_NUM"
)
REFERENCES "WEB_NOV_REPLY" (
	"REPLY_NUM"
);

